=== icl-rocketry/Ricardo-Backend/ricardobackend/flaskinterface/DataRequestTaskSchema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Data Request Task Schema",
    "description": "",
    "type": "object",
    "properties": {
        "task_name": {
            "type": "string"
        },
        "autostart": {
            "type": "boolean"
        },
        "poll_delta": {
            "type": "integer",
            "exclusiveMinimum": 0
        },
        "running": {
            "type": "boolean"
        },
        "logger": {
            "type": "boolean"
        },
        "receiveOnly": {
            "type": "boolean"
        },
        "groups": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "request_config": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 254
                },
                "destination": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 254
                },
                "destination_service": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 254
                },
                "command_id": {
                    "type": "integer",
                    "minimum": 0,
                    "maximum": 254
                },
                "command_arg": {
                    "type": "integer",
                    "minimum": -2147483648,
                    "maximum": 2147483647
                }
            },
            "required": [
                "source",
                "destination",
                "destination_service",
                "command_id",
                "command_arg"
            ]
        },
        "packet_descriptor": {
            "patternProperties": {
                "^.*$": {
                    "anyOf": [
                        {
                            "enum": [
                                "char",
                                "int8_t",
                                "uint8_t",
                                "bool",
                                "int16_t",
                                "uint16_t",
                                "int",
                                "int32_t",
                                "uint32_t",
                                "int64_t",
                                "uint64_t",
                                "float",
                                "double"
                            ]
                        }
                    ]
                }
            },
            "additionalProperties": false
        },
        "bitfield_decoders": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "variable_name": {
                        "type": "string"
                    },
                    "bitfield": {
                        "type": "string"
                    },
                    "flags": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "integer",
                                    "minimum": 0
                                },
                                "description": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "id",
                                "description"
                            ],
                            "additionalProperties": false
                        }
                    }
                },
                "required": [
                    "variable_name",
                    "bitfield",
                    "flags"
                ],
                "additionalProperties": false
            }
        },
        "rxCounter": {
            "type": "integer",
            "minimum": 0
        },
        "txCounter": {
            "type": "integer",
            "minimum": 0
        },
        "connected": {
            "type": "boolean"
        },
        "lastReceivedPacket": {
            "type": "string"
        },
        "rxBytes": {
            "type": "integer",
            "minimum": 0
        },
        "txBytes": {
            "type": "integer",
            "minimum": 0
        }
    },
    "required": [
        "task_name",
        "autostart",
        "poll_delta",
        "running",
        "logger",
        "receiveOnly",
        "groups",
        "request_config",
        "packet_descriptor",
        "bitfield_decoders",
        "rxCounter",
        "txCounter",
        "connected",
        "lastReceivedPacket",
        "rxBytes",
        "txBytes"
    ],
    "additionalProperties": false
}

=== icl-rocketry/Ricardo-Backend/Config/DataRequestTaskConfig.json
[
 {
  "task_name": "emb_fc_telem",
  "autostart": false,
  "poll_delta": 250,
  "running": false,
  "logger": true,
  "receiveOnly": false,
  "groups": [
   "pickle"
  ],
  "request_config": {
   "source": 1,
   "destination": 2,
   "destination_service": 2,
   "command_id": 8,
   "command_arg": 0
  },
  "packet_descriptor": {
   "pn": "float",
   "pe": "float",
   "pd": "float",
   "vn": "float",
   "ve": "float",
   "vd": "float",
   "an": "float",
   "ae": "float",
   "ad": "float",
   "roll": "float",
   "pitch": "float",
   "yaw": "float",
   "q0": "float",
   "q1": "float",
   "q2": "float",
   "q3": "float",
   "lat": "float",
   "lng": "float",
   "alt": "int",
   "sat": "uint8_t",
   "ax": "float",
   "ay": "float",
   "az": "float",
   "h_ax": "float",
   "h_ay": "float",
   "h_az": "float",
   "gx": "float",
   "gy": "float",
   "gz": "float",
   "mx": "float",
   "my": "float",
   "mz": "float",
   "baro_temp": "float",
   "baro_press": "float",
   "baro_alt": "float",
   "logic_voltage": "int32_t",
   "dep_voltage": "int32_t",
   "dep_current": "int32_t",
   "launch_lat": "float",
   "launch_lng": "float",
   "launch_alt": "int",
   "system_status": "uint32_t",
   "system_time": "uint64_t",
   "rssi": "int16_t",
   "snr": "float"
  },
  "bitfield_decoders": [
   {
    "variable_name": "state",
    "bitfield": "system_status",
    "flags": [
     {
      "id": 0,
      "description": "DEBUG"
     },
     {
      "id": 1,
      "description": "PREFLIGHT"
     },
     {
      "id": 2,
      "description": "LAUNCH"
     },
     {
      "id": 3,
      "description": "FLIGHT"
     },
     {
      "id": 4,
      "description": "RECOVERY"
     },
     {
      "id": 5,
      "description": "SETUP"
     },
     {
      "id": 6,
      "description": "GROUNDSTATION"
     }
    ]
   },
   {
    "variable_name": "flag_info",
    "bitfield": "system_status",
    "flags": [
     {
      "id": 7,
      "description": "DEBUG"
     }
    ]
   },
   {
    "variable_name": "flag_error",
    "bitfield": "system_status",
    "flags": [
     {
      "id": 8,
      "description": "SPI"
     },
     {
      "id": 9,
      "description": "I2C"
     },
     {
      "id": 10,
      "description": "SERIAL"
     },
     {
      "id": 11,
      "description": "LORA"
     },
     {
      "id": 12,
      "description": "BARO"
     },
     {
      "id": 13,
      "description": "BATT"
     },
     {
      "id": 14,
      "description": "GPS"
     },
     {
      "id": 15,
      "description": "IMU"
     },
     {
      "id": 16,
      "description": "H_ACCEL"
     },
     {
      "id": 17,
      "description": "MAG"
     },
     {
      "id": 18,
      "description": "ESTIMATOR"
     },
     {
      "id": 19,
      "description": "SD"
     },
     {
      "id": 20,
      "description": "FLASH"
     },
     {
      "id": 21,
      "description": "CAN"
     },
     {
      "id": 22,
      "description": "FLIGHTCHECK"
     },
     {
      "id": 23,
      "description": "ORIENTATION"
     },
     {
      "id": 24,
      "description": "BATT"
     }
    ]
   },
   {
    "variable_name": "flightphase",
    "bitfield": "system_status",
    "flags": [
     {
      "id": 25,
      "description": "BOOST"
     },
     {
      "id": 26,
      "description": "COAST"
     },
     {
      "id": 27,
      "description": "APOGEE"
     },
     {
      "id": 28,
      "description": "DROGUE CHUTE"
     },
     {
      "id": 29,
      "description": "MAIN CHUTE"
     }
    ]
   }
  ],
  "rxCounter": 0,
  "txCounter": 0,
  "connected": true,
  "lastReceivedPacket": "",
  "rxBytes": 0,
  "txBytes": 0
 },
 {
  "task_name": "emb_toothless_telem",
  "autostart": false,
  "poll_delta": 250,
  "running": false,
  "logger": true,
  "receiveOnly": false,
  "request_config": {
   "source": 1,
   "destination": 10,
   "destination_service": 10,
   "command_id": 1,
   "command_arg": 0
  },
  "groups": [
   "stark",
   "emb"
  ],
  "packet_descriptor": {
   "state": "uint16_t",
   "value": "int32_t"
  },
  "bitfield_decoders": [
   {
    "variable_name": "component_status",
    "bitfield": "state",
    "flags": [
     {
      "id": 0,
      "description": "NOMINAL"
     },
     {
      "id": 1,
      "description": "DISARMED"
     },
     {
      "id": 6,
      "description": "ERROR"
     }
    ]
   },
   {
    "variable_name": "toothless_state",
    "bitfield": "value",
    "flags": [
     {
      "id": 0,
      "description": "DEFAULT"
     },
     {
      "id": 1,
      "description": "ARMED"
     },
     {
      "id": 2,
      "description": "IGNITION"
     },
     {
      "id": 3,
      "description": "CONTROLLED"
     },
     {
      "id": 4,
      "description": "SHUTDOWN"
     },
     {
      "id": 5,
      "description": "DEBUG"
     }
    ]
   },
   {
    "variable_name": "controller_errors",
    "bitfield": "value",
    "flags": [
     {
      "id": 0,
      "description": "NOMINAL"
     },
     {
      "id": 1,
      "description": "DISARMED"
     },
     {
      "id": 6,
      "description": "ERROR"
     }
    ]
   }
  ],
  "rxCounter": 0,
  "txCounter": 0,
  "connected": true,
  "lastReceivedPacket": "",
  "rxBytes": 0,
  "txBytes": 0
 },
 {
  "task_name": "emb_stark_telem",
  "autostart": false,
  "poll_delta": 500,
  "running": false,
  "logger": true,
  "receiveOnly": false,
  "groups": [
   "stark",
   "emb",
   "radio"
  ],
  "request_config": {
   "source": 1,
   "destination": 10,
   "destination_service": 2,
   "command_id": 1,
   "command_arg": 0
  },
  "packet_descriptor": {
   "servoVoltage": "float",
   "ch0sens": "float",
   "ch1sens": "float",
   "ch2sens": "float",
   "ch3sens": "float",
   "ch4sens": "float",
   "ch5sens": "float",
   "temp": "float",
   "flowmeter": "float",
   "oxAngle": "uint32_t",
   "fuelAngle": "uint32_t",
   "impulse": "float",
   "system_status": "uint32_t",
   "system_time": "uint64_t"
  },
  "bitfield_decoders": [
   {
    "variable_name": "state",
    "bitfield": "system_status",
    "flags": [
     {
      "id": 0,
      "description": "STATE_IDLE"
     }
    ]
   }
  ],
  "rxCounter": 0,
  "txCounter": 0,
  "connected": true,
  "lastReceivedPacket": "",
  "rxBytes": 0,
  "txBytes": 0
 },
 {
  "task_name": "emb_pyro_main_telem",
  "autostart": false,
  "poll_delta": 1000,
  "running": false,
  "logger": true,
  "receiveOnly": false,
  "groups": [
   "emb",
   "stark",
   "pyro"
  ],
  "request_config": {
   "source": 1,
   "destination": 10,
   "destination_service": 20,
   "command_id": 1,
   "command_arg": 0
  },
  "packet_descriptor": {
   "state": "uint16_t",
   "value": "int32_t"
  },
  "bitfield_decoders": [
   {
    "variable_name": "component_status",
    "bitfield": "state",
    "flags": [
     {
      "id": 0,
      "description": "NOMINAL"
     },
     {
      "id": 1,
      "description": "DISARMED"
     },
     {
      "id": 3,
      "description": "ERROR_CONTINUITY"
     },
     {
      "id": 6,
      "description": "ERROR"
     }
    ]
   }
  ],
  "rxCounter": 0,
  "txCounter": 0,
  "connected": true,
  "lastReceivedPacket": "",
  "rxBytes": 0,
  "txBytes": 0
 },
 {
  "task_name": "emb_ox_main_telem",
  "autostart": false,
  "poll_delta": 500,
  "running": false,
  "logger": true,
  "receiveOnly": false,
  "groups": [
   "stark",
   "servo",
   "emb"
  ],
  "request_config": {
   "source": 1,
   "destination": 10,
   "destination_service": 11,
   "command_id": 1,
   "command_arg": 0
  },
  "packet_descriptor": {
   "state": "uint16_t",
   "value": "int32_t"
  },
  "bitfield_decoders": [
   {
    "variable_name": "component_status",
    "bitfield": "state",
    "flags": [
     {
      "id": 0,
      "description": "NOMINAL"
     },
     {
      "id": 1,
      "description": "DISARMED"
     },
     {
      "id": 6,
      "description": "ERROR"
     }
    ]
   }
  ],
  "rxCounter": 0,
  "txCounter": 0,
  "connected": true,
  "lastReceivedPacket": "",
  "rxBytes": 0,
  "txBytes": 0
 },
 {
  "task_name": "emb_fuel_main_telem",
  "autostart": false,
  "poll_delta": 250,
  "running": false,
  "logger": true,
  "receiveOnly": false,
  "groups": [
   "stark",
   "servo",
   "emb"
  ],
  "request_config": {
   "source": 1,
   "destination": 10,
   "destination_service": 12,
   "command_id": 1,
   "command_arg": 0
  },
  "packet_descriptor": {
   "state": "uint16_t",
   "value": "int32_t"
  },
  "bitfield_decoders": [
   {
    "variable_name": "component_status",
    "bitfield": "state",
    "flags": [
     {
      "id": 0,
      "description": "NOMINAL"
     },
     {
      "id": 1,
      "description": "DISARMED"
     },
     {
      "id": 6,
      "description": "ERROR"
     }
    ]
   }
  ],
  "rxCounter": 0,
  "txCounter": 0,
  "connected": true,
  "lastReceivedPacket": "",
  "rxBytes": 0,
  "txBytes": 0
 },
 {
  "task_name": "emb_greg0_telem",
  "autostart": false,
  "poll_delta": 250,
  "running": false,
  "logger": true,
  "receiveOnly": false,
  "groups": [
   "greg",
   "emb",
   "radio"
  ],
  "request_config": {
   "source": 1,
   "destination": 11,
   "destination_service": 2,
   "command_id": 8,
   "command_arg": 0
  },
  "packet_descriptor": {
   "Feedforward": "float",
   "OxTankP": "float",
   "N2TankP": "float",
   "regAngle": "uint32_t",
   "Proportional_Term": "float",
   "Kp": "float",
   "TC0": "float",
   "system_status": "uint32_t",
   "system_time": "uint64_t"
  },
  "bitfield_decoders": [
   {
    "variable_name": "state",
    "bitfield": "system_status",
    "flags": [
     {
      "id": 0,
      "description": "STATE_IDLE"
     }
    ]
   }
  ],
  "rxCounter": 0,
  "txCounter": 0,
  "connected": true,
  "lastReceivedPacket": "",
  "rxBytes": 0,
  "txBytes": 0
 },
 {
  "task_name": "emb_ereg0_telem",
  "autostart": false,
  "poll_delta": 250,
  "running": false,
  "logger": true,
  "receiveOnly": false,
  "groups": [
   "greg",
   "emb"
  ],
  "request_config": {
   "source": 1,
   "destination": 11,
   "destination_service": 10,
   "command_id": 1,
   "command_arg": 0
